spring:
  application:
    name: Library API
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #none -> padrao, create-drop -> cria o banco quando roda o app e dropa quando encerra (bom para testes de integracao)
      #Em algumas empresas nao eh possivel utilizar o ddl-auto. Por isso eh melhor criar os scripts sql